server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/arte
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: Hyosung
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      location: /Users/superstar_pkb/project/BitCamp Team Project V2/ArtFile
      max-request-size: 30MB
      max-file-size: 30MB

security:
  jwt:
    secret: secret-value

shop:
  upload:
    path: /Users/superstar_pkb/project/BitCamp Team Project V2/ArtFile

UserController:
  signup: Creates user and returns its JWT token
  signin: Authenticates user and returns its JWT token